services:

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  django:

    build: 
      # ./edu_cool
      secrets: 
        - server_cred_username
        - server_cred_pass
      context: ./edu_cool

    ports:
      - "8000:8000"
    env_file:
      - ./edu_cool/.env

    volumes:
      - ./edu_cool:/app
      - /app/app/static/
      - /app/node_modules
      - /app/.venv

    depends_on:
      - redis

    # secrets:
    #   - server_cred_username
    #   - server_cred_pass

  sfu:
    build: ./sfu

    volumes:
      - ./sfu:/app
      - /app/node_modules

    depends_on:
      - django

    tty: true

    stdin_open: true

    secrets:
      - server_cred_username
      - server_cred_pass


secrets:

  server_cred_username:
    file: ./secret0.txt

  server_cred_pass:
    file: ./secret1.txt
